version: "3.8"
services:
  firebird:
    image: "jacobalberty/firebird:2.5.9-ss"
    volumes: 
      - "C:\\JBSoftware\\JBCepilW40\\Banco:/firebird/data"
      - "C:\\JBSoftware\\JBCepilW40\\Backup:/firebird/Backup"       
    ports: 
      - "3050:3050"